# Default values for community-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: yhc0818/sac-community
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

service:
  type: ClusterIP
  port: 8000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

istio:
  namespace: istio-system
  domain: sac.prod.cluster.yanychoi.com
  clusterIssuer: letsencrypt-prod
  prefix: /api/community
  ingressGateway: istio-system/sac-ingress-gw
  egressGateway: istio-system/sac-egress-gw
db:
  url: community-db-svc.community-service.svc.cluster.local
  password: "1234"
otel:
  endpoint: http://tempo.tempo.svc.cluster.local:4317