apiVersion: v1
kind: ConfigMap
metadata:
  name: calendar-db-configmap
  namespace: calendar-service
data:
  initdb.sql: |
    CREATE TABLE Schedule (
        ScheduleID int PRIMARY KEY AUTO_INCREMENT,
        UserID VARCHAR(512) NOT NULL,
        ScheduleName VARCHAR(45) NOT NULL,
        StartTime DATETIME NOT NULL,
        EndTime DATETIME NOT NULL,
        ScheduleDesc VARCHAR(45)
    );