apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ops-apps
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: apps
  
  source:
    repoURL: https://github.com/gcu-sac/argo-cd.git
    targetRevision: HEAD
    path: apps/ops
  
  destination:
    server: https://kubernetes.default.svc
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: default
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true