apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calendar-service
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: apps
  
  source:
    repoURL: https://github.com/gcu-sac/argo-cd.git
    targetRevision: HEAD
    path: charts/prod/calendar-service
  
  destination:
    server: https://kubernetes.default.svc
    namespace: calendar-service
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true