apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-db-configmap
  namespace: auth-service
data:
  initdb.sql: |
    CREATE TABLE sac.users (
      `user_id` INT AUTO_INCREMENT,
      `age` int,
      `city` varchar(180),
      `email` varchar(256),
      `image_url` varchar(256),
      `nickname` varchar(256),
      `password` varchar(256),
      `access_token` varchar(1024),
      `refresh_token` varchar(256),
      `real_email` varchar(512),
      `role` varchar(256),
      `social_id` varchar(256),
      `social_type` varchar(256),
      PRIMARY KEY (`user_id`)
    );