apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-db-configmap
  namespace: auth-service
data:
  initdb.sql: |
    CREATE TABLE IF NOT EXISTS sac.users (
      `num` INT AUTO_INCREMENT,
      `id` varchar(512),
      `email` varchar(256),
      `password` varchar(512),
      `nickname` varchar(256),
      `access_token` varchar(1024),
      PRIMARY KEY (`num`)
    );