apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "auth-service.fullname" . }}-ingress
spec:
  hosts:
  - {{ .Values.istio.domain }}
  gateways:
  - {{ .Values.istio.ingressGateway }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.prefix }}
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "auth-service.fullname" . }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "auth-service.fullname" . }}-egress
spec:
  hosts:
  - {{ .Values.istio.domain }}
  gateways:
  - {{ .Values.istio.egressGateway }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.prefix }}
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "auth-service.fullname" . }}