apiVersion: v1
kind: Service
metadata:
  name: community-db-svc
  namespace: community-service
spec:
  selector:
    app: community-db
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306