apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: community-db
  namespace: community-service
spec:
  selector:
    matchLabels:
      app: community-db
  serviceName: community-db-svc
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: community-db
        sidecar.istio.io/inject: "false"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:8.0.33
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
              - name: community-db-pvc
                mountPath: /var/lib/mysql
              - name: mysql-init
                mountPath: /docker-entrypoint-initdb.d
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1234"
            - name: MYSQL_DATABASE
              value: sac
      volumes:
        - name: mysql-init
          configMap:
            name: community-db-configmap
  volumeClaimTemplates:
    - metadata:
        name: community-db-pvc
        namespace: community-service
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 10Gi