apiVersion: v1
kind: Service
metadata:
  name: {{ include "calendar-service.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /api/calendar/actuator/prometheus
    prometheus.io/port: "8080"
  labels:
    {{- include "calendar-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "calendar-service.selectorLabels" . | nindent 4 }}
