apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-gw-cert
  namespace: istio-system # istio 설치경로
spec:
  secretName: grafana-gw-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: grafana.prod.cluster.yanychoi.site
  dnsNames:
  - grafana.prod.cluster.yanychoi.site
---
kind: Gateway
apiVersion: networking.istio.io/v1beta1
metadata:
  name: grafana-gw
  namespace: grafana
spec:
  servers:
    - hosts:
        - grafana.prod.cluster.yanychoi.site
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: grafana-gw-tls
        mode: SIMPLE
    - hosts:
        - grafana.prod.cluster.yanychoi.site
      port:
        name: http
        number: 80
        protocol: HTTP
  selector:
    app: istio-ingressgateway

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grafana
  namespace: grafana
spec:
  hosts:
  - grafana.prod.cluster.yanychoi.site
  gateways:
  - grafana-gw
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: grafana