apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sac-gateway
  namespace: argo-cd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  
  source:
    repoURL: https://github.com/gcu-sac/argo-cd.git
    targetRevision: HEAD
    path: charts/ops/istio
  
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  
  syncPolicy:
    automated: 
      prune: false
      selfHeal: false
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=true